### ISSUE TITLE
addRule 执行顺序不正确

### ISSUE THREAD

**Issue by Kage336** [rsuite/schema-typed#11]
addRule 执行顺序不正确，超过3个以上的规则，addRule  的执行优先级会高于普通的后续规则

**Comment by simonguo** [comment]
https://github.com/rsuite/schema-typed#%EF%B8%8F-notes

Check priority:
- 1.isRequired
- 2.addRule
- 3.Predefined rules (if there is no isRequired, value is empty, the rule is not executed)

**Comment by Kage336** [comment]
执行顺序不是应该按照我链式调用的顺序吗？

**Comment by simonguo** [comment]
`isRequired` 和  `addRule` 这两个比较特殊， 预定义的函数都是链式的顺序。

**Comment by Kage336** [comment]
能否改成都按链式调用的顺序呢，现在的报错提示顺序不可控，有些场景没法写呀

**Comment by simonguo** [comment]
@Kage336  你什么样的场景不可控，能举例说明一下吗？

**Comment by Kage336** [comment]
比如
---------------------- >
请输入电话号码: xxxxxxx
再次输入电话号码: xxxxxxx
---------------------- >
我希望 是否填写 -> 是否是合法的电话号码 -> 是否和上面填写一致

**Comment by Kage336** [comment]
是否是合法的电话号码 使用的是内置方法
 是否和上面填写一致 使用的是addRule

现在 会先校验是否一致，再校验是否是合法的电话号码

报错文案不是我所希望得到的

**Comment by simonguo** [comment]
@Kage336  明白，我想想看看怎么做成可配置的，调整一下，如果你有什么建议，可以给我们提 PR

**Comment by Kage336** [comment]
我觉得直接按链式调用的顺序最好用 。。。

**Comment by simonguo** [comment]
还是会有优先级的，比如 `isRequired`

**Comment by simonguo** [comment]
```
npm i schema-typed@1.1.0
```
