### ISSUE TITLE
无法做到异步校验

### ISSUE THREAD

**Issue by guowenfh** [rsuite/schema-typed#13]
场景：某个值一定需要通过一个接口，或者一些异步的方法进行校验。现在没办法做到。。

推荐使用 结合 async/await 与 Promise 的 resolve 表示校验成功 与 reject 表示校验失败 来实现。

**Comment by guowenfh** [comment]
我们在某种程度上也可以把 Promise 看作是纯函数。 （一定会返回resolve 或者reject）

**Comment by simonguo** [comment]
这确实是一个常用的需求，我考虑下一下，想想怎么改进一下(或者提供一种解决方案)。
你如果有什么好的方式也可以给我们提 PR.

**Comment by simonguo** [comment]
```
schema-typed@1.2.0 
```
新增对异步校验的支持，在 addRule 可以返回一个 Promise ， 通过执行 `model.checkAsync` 触发校验。

https://github.com/rsuite/schema-typed/blob/master/README_zh.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%AA%8C%E8%AF%81---%E5%BC%82%E6%AD%A5%E6%A0%A1%E9%AA%8C

**Comment by guowenfh** [comment]
棒！

**Comment by guowenfh** [comment]
这个 api 加了之后，比较接近理想中的校验了，很简洁。本来以为会直接在原有api改的，没想到加了一个 async。

能整体/单个校验，也支持夸字段和异步校验！比 async-validator 使用好很多。

不过 async-validator 有好的一点是 部分校验可以做到配置式，json schema

这个应该可以通过一个包装器实现。。我去组里先宣传一波
