### ISSUE TITLE
RegEx for URL doesn't match `mailto:` URL

### ISSUE THREAD

**Issue by t83714** [rsuite/schema-typed#45]
### What version of schema-typed are you using?

5.13.0

### Describe the Bug

The regex expression used by the `isURL` method doesn't match mailto URL e.g. `mailto:someone@yoursite.com`

https://github.com/rsuite/schema-typed/blob/893a1654514d854dfd321158f9c650c221f31871/src/StringType.ts#L80

### Expected Behavior

The above regex should match string `mailto:someone@yoursite.com`

### To Reproduce

Test the above regex at https://www.regextester.com/

**Comment by rokejulianlockhart** [comment]
I was provided similar RegEx by https://stackoverflow.com/questions/25703360/regular-expression-extract-subdomain-domain#comment40178155_25703800

```regex
^(?!mailto:)(?:(?:http|https|ftp)://)(?:\\S+(?::\\S*)?@)?(?:(?:(?:[1-9]\\d?|1\\d\\d|2[01]\\d|22[0-3])(?:\\.(?:1?\\d{1,2}|2[0-4]\\d|25[0-5])){2}(?:\\.(?:[0-9]\\d?|1\\d\\d|2[0-4]\\d|25[0-4]))|(?:(?:[a-z\\u00a1-\\uffff0-9]+-?)*[a-z\\u00a1-\\uffff0-9]+)(?:\\.(?:[a-z\\u00a1-\\uffff0-9]+-?)*[a-z\\u00a1-\\uffff0-9]+)*(?:\\.(?:[a-z\\u00a1-\\uffff]{2,})))|localhost)(?::\\d{2,5})?(?:(/|\\?|#)[^\\s]*)?$
```

any idea of the origin of it?

**Comment by SevenOutman** [comment]
According to [RFC 2368](https://www.ietf.org/rfc/rfc2368.txt), a `mailto` link is also a type of URL, thus `isURL` rule should be matching `mailto` links, or at least provide an option to enable it.
