### ISSUE TITLE
The errorMessage of `NumberType().range` is wrong

### ISSUE THREAD

**Issue by imyuanx** [rsuite/schema-typed#68]
### What version of schema-typed are you using?

2.1.2

### Describe the Bug
Same to https://github.com/rsuite/rsuite/issues/3164

### Expected Behavior

Obtain normal error information

### To Reproduce

I can try to fix it

**Comment by SevenOutman** [comment]
@imyuanx Thank you for being helpful. I've just reviewed your PR
